require "$sourcedir/xYsyD2QRDvks.pl";
sub lock{xdUYUhmAbJF(@_)}
sub unlock{xpeFJer25Gq2(@_)}
sub getOnlineName{xFJpjUZYMRAQ(@_)}
sub isOnline{xN99wAdDgI3s(@_)}
sub getOnlineInfo{xDUrH77sawno(@_)}
sub writeOnlineInfo{xvvtnsV4JuQ(@_)}
sub addOnlineInfo{x5GkmgJjHbbU(@_)}
sub kickUser{x9Bs9cdstn(@_)}
sub getMemberInfo{xOcTa0KVV0vs(@_)}
sub writeMemberInfo{x1kUrDaEzCNA(@_)}
sub getRoomInfo{xVOZKuRfVaJA(@_)}
sub writeRoomInfo{x0V7DuLVZHHc(@_)}
sub completeName{xduycyiEAak(@_)}
sub completeMember{xJmmvFPnL5w2(@_)}
sub addToMemberList{xCgtRhj9dsgs(@_)}
sub toFilename{xykYDEOyWEzA(@_)}
sub fromFilename{xj633LuX3Js(@_)}
sub UserExists{xtRZhgIrGkJo(@_)}
sub addToRoomList{xVjHns7jBXOQ(@_)}
sub writeSettingsFile{xN5nSt3BUz1o(@_)}
sub readlock{xzjYW5VOv4Zo(@_)}
sub lcase{xpqh37zcXpI(@_)}
sub ToHTML{xNfLGEa4Vfe2(@_)}
1;
